baseUrl: /cbolyard.github.io
title: Thinking about Data
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
